[[section-introduction-and-goals]]
== Introduction and Goals

Hypothetically, we have been presented with a project by the Brussels City Council to create an application called LoMap. This application will consist of customized maps that city residents can access, where they can share different places in the city such as bars, restaurants, monuments, and so on.

It is also proposed that this application could be extrapolated to other cities, therefore we will aim for high compatibility between the different elements of the architecture. Additionally, we will possible scalability of the project. As stakeholders, we would have the Brussels City Council, our professors who will review and evaluate the development and all the steps taken in the project, and us as students, who will seek to learn and adapt to any difficulties that may arise during development.


=== Requirements Overview

* Add different types of locations (bars, shops, restaurants, landscapes, monuments, etc.).
* Display these places in a Map window.
* Allow users to rate and comment on the added locations.
* Manage the information that users can share with their friends from within the app.
* Store the information about any location in each user's SOLID pod.
* Certain information can be stored centrally for performance reasons, but always respecting the privacy of the users.
* Allow users to view the places and information about them that their friends have shared.
* Provide filtering options for the information displayed on the map (by category, friends, etc.).

=== Quality Goals

* Aesthetics and usability for users with no technical knowledge.
* Security and privacy for users.
* Reliability of the application during use.
* Innovative and usable solution.
* Proper and technical documentation to capture all decisions made by the team.
* Quality of the code, which will be stored manually and automatically.
* Quality of the project's testing strategy.
* Proper project management through the use of issues, meeting minutes, record keeping and monitoring of every decision made by the team throughout the project.
* Use of continuous integration.
* Interoperability of data across different applications that may be developed with the same functionality.

=== Stakeholders

[options="header",cols="1,2,3"]
|===
| *Role/Name* | *Contact* | *Expectations*
| _Profesores_ | _labra@univovi.es_ | _Learning and proper functioning of the team during the development of the project._
| _Ayuntamiento de Bruselas_ | _https://www.bruxelles.be/hotel-de-ville_ | _Develop a project similar to Google Maps so that users can share certain places in each city._
|===
