[[section-solution-strategy]]
== Solution Strategy

== Tecnologias

Backend

* NodeJS: es un entorno de tiempo de ejecución de JavaScript que se utiliza para crear aplicaciones escalables del lado del servidor y de red a través de servidores privados virtuales.

Frontend

* React: es una biblioteca JavaScript de código abierto diseñada para crear interfaces de usuario con el objetivo de facilitar el desarrollo de aplicaciones en una sola pagina.
* TypeScript: es un lenguaje de programación de código abierto pensado para ejecutar grandes proyectos y que permite trabajar de manera estructurada.

Base de datos

* MongoDb: se utilizara para la creación de la base de datos.

Utilizaremos POD para los usuarios.

== Objetivos

* Privacidad: Utilizaremos PODs para que cada usuario tenga mas seguridad y no sean tan vulnerables.

== Decisiones organizativas

Issues

Cada miembro del equipo creará issues cada vez que vaya a realizar una tarea y asignará que miembros van a realizarla.

Comunicación

La comunicación del equipo se realizará a través de discord y mediante Whatsapp. También mediante las issues se realizara el reparto de tareas.



[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
